---
sudo: false
language: python
python: "2.7"
install: pip install ansible
script:
  - echo 'localhost' > inventory
  - touch vars.yml
  - ansible-playbook -i inventory playbook.yml --syntax-check
notifications:
  email:
    on_success: never
    on_failure: always
